# Generated by Django 4.1.3 on 2023-01-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_newscategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'News categories'},
        ),
    ]
